/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LogoRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'imageUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'shirtColor' : IDL.Text,
  'vinylColor' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'shirtType' : IDL.Text,
  'category' : IDL.Text,
});
export const OrderV2 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'cartItems' : IDL.Vec(CartItem),
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'releasedAt' : IDL.Int,
  'price' : IDL.Nat,
});
export const NewLogoRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'imageUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const NewOrder = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'cartItems' : IDL.Vec(CartItem),
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});

export const OrderFinancials = IDL.Record({
  'totalPaid' : IDL.Int,
  'depositPaid' : IDL.Int,
  'paymentMethod' : IDL.Text,
  'dateDelivered' : IDL.Int,
  'costPerShirt' : IDL.Int,
  'pricePerShirt' : IDL.Int,
  'designNotes' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'category' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Int,
  'vendor' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const NewExpense = IDL.Record({
  'date' : IDL.Int,
  'category' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Int,
  'vendor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'getLogoRequests' : IDL.Func([], [IDL.Vec(LogoRequest)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderV2)], ['query']),
  'getVideoLibrary' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'submitLogoRequest' : IDL.Func([NewLogoRequest], [IDL.Nat], []),
  'submitOrder' : IDL.Func([NewOrder], [IDL.Nat], []),
  'addExpense' : IDL.Func([NewExpense], [IDL.Nat], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllOrderFinancials' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, OrderFinancials))], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getOrderFinancials' : IDL.Func([IDL.Nat], [IDL.Opt(OrderFinancials)], ['query']),
  'updateOrderFinancials' : IDL.Func([IDL.Nat, OrderFinancials], [IDL.Bool], []),
  'updateLogoRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LogoRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'imageUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'shirtColor' : IDL.Text,
    'vinylColor' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'shirtType' : IDL.Text,
    'category' : IDL.Text,
  });
  const OrderV2 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'cartItems' : IDL.Vec(CartItem),
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'releasedAt' : IDL.Int,
    'price' : IDL.Nat,
  });
  const NewLogoRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'imageUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const NewOrder = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'cartItems' : IDL.Vec(CartItem),
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  const OrderFinancials = IDL.Record({
    'totalPaid' : IDL.Int,
    'depositPaid' : IDL.Int,
    'paymentMethod' : IDL.Text,
    'dateDelivered' : IDL.Int,
    'costPerShirt' : IDL.Int,
    'pricePerShirt' : IDL.Int,
    'designNotes' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'category' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Int,
    'vendor' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const NewExpense = IDL.Record({
    'date' : IDL.Int,
    'category' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Int,
    'vendor' : IDL.Text,
  });
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'getLogoRequests' : IDL.Func([], [IDL.Vec(LogoRequest)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderV2)], ['query']),
    'getVideoLibrary' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'submitLogoRequest' : IDL.Func([NewLogoRequest], [IDL.Nat], []),
    'submitOrder' : IDL.Func([NewOrder], [IDL.Nat], []),
    'addExpense' : IDL.Func([NewExpense], [IDL.Nat], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllOrderFinancials' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, OrderFinancials))], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getOrderFinancials' : IDL.Func([IDL.Nat], [IDL.Opt(OrderFinancials)], ['query']),
    'updateOrderFinancials' : IDL.Func([IDL.Nat, OrderFinancials], [IDL.Bool], []),
    'updateLogoRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };